### ISSUE TITLE
Sign in/Sign-up with Email via OTP

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#10]
As a user, I want to be able to sign up and signing with my Email to the voting App so I will have another Account Abstracted Address so I can be anonymous and I can play the voting game simply on my mobile.

**Descriptions:**
1- We do sign up and log-in with one-time OTP only. So there's no password, the duration of logged-in token can be a week, so there's no need to ask for OTP if the token is valid.
2- The expiration time of OTP is only 10 Min, users can click on re-send to get the OTP email again. 
3- If users wrote the email wrongly, they can click on edit icon and in this case they get back to the email screen to enter the email again. 
4- If user do the login with email for the first time, so we create an account and map it to his/her email and show the "Pairwise Passport Verified!" screen. 
5- If user has already signed up and just want to login, IF the token expired, we asked them to enter the OTP, and show them the "Account verified successfully" screen.
6- If user already has an account associated with that email address and just want to login, if they has logged in a week ago (token is still valid) they got to dashboard directly. 
7- The 2-B screens only last for 5 sec and the dashboard show up automatically. 
8- If the OTP is not valid or it's not correct we show different toast error messages. 
9- BAck icon will link the user to the first screen. 
10- if otp is correct we show green border for OTP digit and let user to click on SUbmit
11- if we got error we change teh border and the background of 4 digit OTP
12- If the OTP did not entered or it's wrong, we should disable the Submit button. 
13- if user clicks on resend code, we should revoke the previous OTP issues for this user and create new one, count downs are there to avoid user click on resend several times. 

<img width="948" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56513a41b0dae12c2d17f0214f0c52311fd79a39/image.png" alt="image.png" />
<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdd40ea989a927812f98b06273c4dd8e362a5973/image.png" alt="image.png" />
<img width="458" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--813fd310e6e0bf9172cee23d4e70b3ec081c4ff9/image.png" alt="image.png" />

**Design:**
https://www.figma.com/file/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?type=design&node-id=1373-10510&mode=design&t=mkuNIPuKqr8uglIZ-4

**Comment by MoeNick** [comment]
@mmahdigh @alireza-sharifpour success criteria's updated.

**Comment by maryjaf** [comment]
- [ ] 1-

In the email the expired time is shown 15 min but after about 5 min I got an error and couldn’t login 
![IMG_1637](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/f0858c2f-e2f1-4c4d-8ff4-9c9b6fe1ad98)
![IMG_1638](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/911a0678-de52-49da-843d-bb4568c6b746)

**Comment by maryjaf** [comment]
> 4- If user do the login with email for the first time, so we create an account and map it to his/her email and show the "Pairwise Passport Verified!" screen.
> 5- If user has already signed up and just want to login, IF the token expired, we asked them to enter the OTP, and show them the "Account verified successfully" screen.

- [ ] 2-

For these 2 scenarios I've seen the below view
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/f122f2d3-9a9c-4a03-afca-b0cc3bac53fb)

**Comment by mmahdigh** [comment]
> > 4- If user do the login with email for the first time, so we create an account and map it to his/her email and show the "Pairwise Passport Verified!" screen.
> > 5- If user has already signed up and just want to login, IF the token expired, we asked them to enter the OTP, and show them the "Account verified successfully" screen.
> 
> * [ ]  2-
> 
> For these 2 scenarios I've seen the below view ![image](https://private-user-images.githubusercontent.com/111529185/330755980-f122f2d3-9a9c-4a03-afca-b0cc3bac53fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTgyMTQsIm5iZiI6MTcxNjE5NzkxNCwicGF0aCI6Ii8xMTE1MjkxODUvMzMwNzU1OTgwLWYxMjJmMmQzLTlhOWMtNGEwMy1hZmNhLWIwY2MzYmFjNTNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwOTM4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjY1N2E0ZjIyMGJjMGM1YmRjYjRmNThhYzdiMDUzNDc0YjI0N2U1YzFhYWYzYzNjN2QwZTA5MDQyNWRmNTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TG0hLBe-vF84dnZIF6HnHqEKNNC5uWMXBwZ2c64SY-I)

@maryjaf I believe this has been fixed. Would you mind retesting?

**Comment by maryjaf** [comment]
Thanks @mmahdigh item 2 has been resolved.
Now only item 1 should be checked.

**Comment by mmahdigh** [comment]
> Thanks @mmahdigh item 2 has been resolved. Now only item 1 should be checked.

I've checked item 1 and you're right about the bug. However, fixing it is not in our hands honestly. Later today, I'll open an issue for Thirdweb folks to either make the expiration time 15 minutes or edit the email message.

I don't know if we should pursue that process with Thirdweb in this issue or open a separate issue though. @MoeNick @maryjaf

**Comment by MoeNick** [comment]
All the other AC are ok @maryjaf ?

**Comment by maryjaf** [comment]
> I don't know if we should pursue that process with Thirdweb in this issue or open a separate issue though. @MoeNick @maryjaf

Should a separated issue be created for this ? @MoeNick 
If yes we could move it to next state

**Comment by MoeNick** [comment]
Raised another issue and moved it to test done
