### ISSUE TITLE
Put Category descriptions in categories page. 

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pairwise-RPGF4#100]
The data is here : 
https://docs.google.com/document/d/1EqzIVWW--HjzztDv0_N_M_d2ZtOtYhMZlgm49djMpfg/edit?usp=drivesdk

Right now this page does not have any descriptions for categories, but we should provide it like design. 

<img width="281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--728068936bb9d3f23ac7b05e69913c1899712c9e/image.png" alt="image.png" />

Please sync with @mmmahdi if you need to read the from backend.

**Comment by MoeNick** [comment]
Where to put and how to get?

**Comment by MoeNick** [comment]
@lovelgeorge99 I assigned it to you as a P2 priority please take it up when you have bandwidth.

**Comment by MoeNick** [comment]
I tested it and  think the description fonts should follow the design, with smaller fonts. 
@alireza-sharifpour

FYI: @maryjaf
