### ISSUE TITLE
After finalize 2 categories and do pw assesment on categoris got error

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pairwise-RPGF4#101]
![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/f87d92da-8bd6-4db0-9012-110aa4e67a00)

**Comment by MoeNick** [comment]
@maryjaf to reproduce. 

FYI: @mmahdigh

**Comment by mmahdigh** [comment]
This is fixed.
