### ISSUE TITLE
Some copy changes

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pairwise-RPGF4#102]
![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/8c8d28ea-a6b8-4193-a36d-6688ec89396b)
Congratulations! You’ve successfully voted in at least two categories. Now, it’s time to vote for the categories that overall had more impact!

![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/84c2a266-3ab6-491c-a1f8-e7bbbb19d3d9)
Important: You must to at least chose [X] projects
[X]-->21% of the projects

![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/b12e71ed-c6cc-4723-9d71-fcc4834f1562)
17 of 27 Projects filtered

![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/095d37a2-0e26-467a-bdac-391cbb5e038e)
Now they battle to the DEATH!--> Let's find out which projects come out on top!

Red botton [View summary]-->Start Pairwise assesment

**Comment by MoeNick** [comment]
shall I put it in test?

**Comment by Zeptimus** [comment]
![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/4506a5bb-0804-41ef-91b2-3ea1bdb96cb0)
Important: You must at least choose 6 projects.-->Important: You must choose at least 6 projects.

**Comment by MoeNick** [comment]
@mmahdigh can review the related PR

**Comment by maryjaf** [comment]
> Important: You must to at least chose [X] projects
> [X]-->21% of the projects

This change hasn't been applied, please take a look @lovelgeorge99

**Comment by lovelgeorge99** [comment]
> > Important: You must to at least chose [X] projects
> > [X]-->21% of the projects
> 
> This change hasn't been applied, please take a look @lovelgeorge99
@maryjaf 
I changed this on another issue
https://github.com/GeneralMagicio/pairwise-RPGF4/pull/136#event-13294249925

**Comment by maryjaf** [comment]
> Important: You must to at least chose [X] projects
> [X]-->21% of the projects

It hasn't been fixed @MoeNick 

<img width="801" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGlXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3381cb6a424d1cd78d5788dd612c3522a67dadd9/image.png" alt="image.png" />
