### ISSUE TITLE
When launching the app on mobile, there is a page that flashes too fast after the wallet is created

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-RPGF4#108]
I'm sorry i don't have a screen shot, but it all happened so fast!

After the Pikachu Hodl page 
<img width="757" alt="Screenshot 2024-06-23 at 12 44 55 PM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/14945613/08d9233c-b90d-4598-b362-2223259c3938">

there was another page that popped up and disappeared quickly I have no idea what it said.

Was it important?

**Comment by MoeNick** [comment]
When the user gets back from account verification it goes to login page quickly and then redirect to categories change, this was potentially  related to that issue. Getting them back there had a reason to give user tokens or show some errors if wallet connect or login was unsuccessful.
