### ISSUE TITLE
P0 - I am a badgehodler and a delegate and have over 500 OP... yet it gave me the recipient badge

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-RPGF4#110]
I thought the order of operations was:

1. if you are a Badgeholder, you get the Badgholder badge, and if you have over 500 OP you get an OP holder badge as well
2. if you are not a Badgeholder, but you are a delegate you get the delegate badge, but you do not get an OP holder badge
3. if you are not a Badgeholder nor a delegate, but you are a recipient you get the recipient badge, and if you have over 500 OP you get an OP holder badge as well
4.  if you are not a Badgeholder nor a delegate, nor a recipient, but you have over 500 OP you get an OP holder badge

So i should get the badgeholder badge... also i have ~16,000 OP so i should get a OP Holder badge.

**Comment by MoeNick** [comment]
@lovelgeorge99 can you check your CSV and find out the cause?

**Comment by mmahdigh** [comment]
It's ready for retesting. The new CSV from @lovelgeorge99 is up.
