### ISSUE TITLE
P0 - VERY IMPORTANT! Connecting a wallet on mobile is confusing, and as far as I can tell impossible in every way

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-RPGF4#111]
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/14945613/13ec96b8-1dd5-417c-9fca-b34773f90697)

This needs a lot of fixing! I could not figure out how to connect an address on my computer to my phone wallet.

- [ ] Copy needs to change to be more clear in several ways:
1.  Don't want to connect wallet? => "Is your wallet on a different device?"
2. [website] => "website below." (see the next check box)
3. Continue as Guest => "Don't Connect Wallet"
4. Keep in mind that as guests, your votes will not be considered => "If a wallet is never connected you will have no voting power, but you can connect your wallet later."

- [ ] Add another field that makes it super easy to copy paste the website just above the one with the code, so people can copy it to a DM or email and send it to themselves

- [ ] Why doesn't Metamask or some sort of mobile wallet show up as an option? This seems like its using a desktop style discovery tool, but on Mobile its VERY different, I have Trust Wallet, Coinbase Wallet, Metamask and other wallets all installed on my phone but they did not show up here.

NOTE: I'm a little scared. We need to test this A LOT! It is very very likely that people will see a link to Pairwise while looking at twitter on their phone and then play with it there, and their real keys will be on their computer. This has the potential to be the WOW factor for pairwise. I hope we can pull it out in the next few days, otherwise we might need to consider removing Mobile as an option at launch if it is not working properly.

**Comment by GriffGreen** [comment]
Follow Up... I kept trying and couldn't connect at all to my phone, i tried with griff.eth, I also tried with a wallet that has OP... I couldn't get connected. This late in the game, i am leaning towards removing mobile for launch and adding it later... as there is soooooo much wrong here, that i don't know how we could get it all fixed in time.

**Comment by MoeNick** [comment]
I will sync with @mmahdigh on this. 
- I was not in the loop of the "Continue as Guest" feature. 
- The copy changes and copy of the website link with parameter code is something we can fix asap.
- Why doesn't Metamask or some sort of mobile wallet show up as an option? This was a tech decision not to use Web3Modal and they are using WAGMI, WAGME only detects the previously web-injected wallets. From @alireza-sharifpour and WAGME doc:
Warning This connector has a large file size due to the underlying @metamask/sdk. For mobile support, it is recommended to use walletConnect . For desktop support, you should rely on Multi Injected Provider Discovery (EIP-6963) via the Wagmi Config .
- So users can use Walletconnect in this case if they did not connect as before. 
- Did you copy the OTP and try pasting it on the desktop webpage? @GriffGreen

**Comment by jainkrati** [comment]
Assigning to @alireza-sharifpour and @MoeNick

**Comment by mmahdigh** [comment]
This is ready for retesting.

With just one [caveat](https://discord.com/channels/@me/1208020689802760192/1254803734777561138).

**Comment by maryjaf** [comment]
The below pic is  is the new design , based on @MoeNick comment this change should be applied
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/80c589f3-49e3-4800-8759-8bccf2add6f4)

- [ ] 1- use black  normal font instead of red And truncated text in url section

**Comment by maryjaf** [comment]
- [ ] 2- It would be good if user taps on copy icon, a message like "copied" be shown 

- [ ] 3- there is a problem in connect wallet with Metamask, please take a look on below screen records


@mmahdigh

**Comment by MoeNick** [comment]
For number 2 please use a toast message with this text `Copied.` It would glance only one second below the box. each time the user clicks on the copy icon it would show up. 
And this format 
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/80677512/492e3378-8f3c-41b3-9fcb-1206c2fd6610)
Find it here : https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1364-2531&t=I5Otsv80c5FpTPrD-4
@mmahdigh

**Comment by maryjaf** [comment]
- [ ] 4- today I get 401 error in login flow

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/10768c17-e681-4ba4-8374-d644037372bc)

**Comment by mmahdigh** [comment]
Added the "Copied" toast message + the color change.

**Comment by MoeNick** [comment]
@maryjaf should I put it to done? copied worked fine.

**Comment by maryjaf** [comment]
> * 3- there is a problem in connect wallet with Metamask, please take a look on below screen records

.

**Comment by mmahdigh** [comment]
> > * 3- there is a problem in connect wallet with Metamask, please take a look on below screen records
> 
> .

This view is desktop-only. We'll soon disable it on mobile altogether.
