### ISSUE TITLE
P2 - Why did the instructions to connect wallet show up on mobile... if a user gets here on mobile, we should tell them to go to desktop

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-RPGF4#112]
![signal-2024-06-22-140203_002](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/14945613/9ed3cf69-f888-43f8-86db-8b8f09208fca)

Some how i was able to navigate to this page on my mobile phone... but I think instead if i'm on mobile and i navigate to his page, i should see a splash page that says:

"Go to the device with your OP account and connect it pseudonymously to this device." and then give it the website and code to copy, as mentioned in #111

**Comment by MoeNick** [comment]
We should disable this flow on mobile IMO. 
Shall we @mmahdigh?

**Comment by MoeNick** [comment]
@griffGreen, when we show them the OTP and the link, we're saying if you have your wallet on the "other device", this could have this assumption that the device is another mobile device. Otherwise, we can disable this view in desktop and let them know to open it up in desktop.

**Comment by MoeNick** [comment]
Final Decision:

- Detect user is on mobile device or not
- If user is on mobile, show an splash page with this text: `Go to the device with your OP account and connect it pseudonymously to this device`
-

**Comment by maryjaf** [comment]
It was moved to test yesterday, I'll check it

**Comment by maryjaf** [comment]
there is no difference between mobile and desktop view in this page https://staging.app.pairwise.vote/connect

**Comment by lovelgeorge99** [comment]
You should see a pop up message when u visit this page in mobile view
![pop](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/36924734/2960f6f2-c75e-46ba-a3c6-bcdb0dc77712)

**Comment by maryjaf** [comment]
Thanks @lovelgeorge99 
This issue has been resolved.
