### ISSUE TITLE
P1 - The OTP page still says delegate on the button and needs a few other updates

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-RPGF4#114]
This is blocked by #111 

In the end, this page only matters if we can get the OTP to actually work reliably... which i couldn't. 

<img width="648" alt="Screenshot 2024-06-23 at 9 51 29 PM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/14945613/d29d654d-acab-456e-8ca4-9fd02571806f">

- [x] Remove the scroll bars on the numbers... there is no reason for those to pop up.
- [x] Paste the OTP from Pairwise. => `Paste the OTP from your other device.`
- [x] How to get OTP? has an "i" but there is no tool tip for it....
- [x] Error message: Not able to connect you to a user. Please try again later => Please try again
- [x] The Delegate button should should be => `Connect`

**Comment by MoeNick** [comment]
As it's related to #111 @mmahdigh will take care of it.

**Comment by MoeNick** [comment]
FYI @maryjaf some other buttep points and copy changes are here to fix related to this screen.

**Comment by mmahdigh** [comment]
It's ready for testing.

**Comment by maryjaf** [comment]
All items have been applied
