### ISSUE TITLE
After round: Reward Banner

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#119]
When the round is up and we have the greenlight from UniTap. Only for users who won the grant, we should show this banner. 

<img width="645" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemVIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bb416e261a19005e29278dd8cef11b55f40fee1/image.png" alt="image.png" />

- Design Resource: https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=5614-14416&t=yY3XMYZOVWrPFXsR-11
- Link Destination: will update in comments next week

**Comment by Zeptimus** [comment]
i like black :-D

**Comment by MoeNick** [comment]
@Zeptimus appreciate it if you can give us the link.

**Comment by Zeptimus** [comment]
Your activity and support deserve a prize! Unwrap your special reward now.-->You've got a chance to claim OP! Click 'Check Eligibility' to see if you're eligible. Don't forget to review your badge group and check which raffles you can enter

Claim now--> Check elegibility

**Comment by maryjaf** [comment]
<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9VQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a400d35d4459ff345d8ddff6cae7fd48b7f2fb8/image.png" alt="image.png" />
