### ISSUE TITLE
[BUG]  - I can't login with my email

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/pairwise-RPGF4#125]
**Describe the bug**
I tried logging into Pairwise with my personal email (with the one time login code). I get the login code fine, but when I enter it, the page gets stuck on this (over 5 minutes and nothing is happening): 

<img width="785" alt="Screenshot 2024-06-25 at 12 32 51 PM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/4855928/9f76b7b8-7c45-4178-a50d-e69b9b78411c">

Then when I refreshed the page after waiting 5 minutes I got this error

<img width="950" alt="Screenshot 2024-06-25 at 12 34 44 PM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/4855928/e5f9ed32-151f-41df-a624-084bf261b13a">

and when I check Console I see this error

<img width="1413" alt="Screenshot 2024-06-25 at 12 51 34 PM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/4855928/d62411ec-2597-4191-b81f-881809f092b9">

Let me know if you need any more clarification @MoeNick @Zeptimus

**Comment by MoeNick** [comment]
We had some devOps problem in production, can you retest please? @ahmadabugosh
