### ISSUE TITLE
[BUG] Learn more flow looks wierd

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pairwise-RPGF4#128]
![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/1a4a848a-b335-4bfb-9f1c-e531e105d715)

When clicking learn more the icon disapears

**Comment by MoeNick** [comment]
it's because we don't have data there.

**Comment by MoeNick** [comment]
@mmahdigh supposed to check if there's issues with data or something else.

**Comment by mmahdigh** [comment]
This is fixed. Please retest.
