### ISSUE TITLE
[BUG] Mouse looks like wanting to eddit

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pairwise-RPGF4#129]
![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/ff4f1524-5dc5-4c74-92d7-ed279bbcd2ba)

Check where the cursoer is instead of giving select vibe it gives edit vibe with this simbol I

**Comment by MoeNick** [comment]
@alireza-sharifpour we should keep both upper logo and lower logo clickable and cursor looks like link in desktop mode.
