### ISSUE TITLE
UX change on inset OTP | Desktop Flow

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#147]
<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTJYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6fa7a34d0a8f992a00fc59e592810bb2b504b5f/image.png" alt="image.png" />

1- keep the sunny but remove the underneath text. 

2- use that copy in the second picture - Remove tge OTP and text and have these:
<img width="416" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1YQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ce6db64b1035fa93ba4d503bf12a6052d196983/image.png" alt="image.png" />

- Claim Badges
- Claim your badges to start voting on projects.
- n badges found
- showing the badges

3- Change the copy to connect. 

4- The same flow for mobile when user don't have any badges. 
<img width="445" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2436023265a4b62ab198eb01bb5d565c6d222a9/image.png" alt="image.png" />

Note the copy of button should be "connect anyway"

**Comment by MoeNick** [comment]
For error:
`There's no Pairwise account associated with your link. Please get back to the Mobile App and try a new link. `
https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1364-2530&t=pKFmYuI53wbFxDXN-4

**Comment by alireza-sharifpour** [comment]
This new flow is ready for testing @maryjaf
