### ISSUE TITLE
List of categories and their status

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#15]
As a user I want to see the category list of projects, with their status, to know which category I started filtering, ranking and which of them are done. 
<img width="543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15384b3c366fbfc5a24e3e5e3e8e456dd6549ad9/image.png" alt="image.png" />

### **Success Criteria:**

- [ ] List view and card view
- [x] User should automatically see this page after successful login / register. 
- [x] statuses should be ranked, ranking, filtering or filtered and "not ranked".  The flow is like this:  not ranked -> filtering -> filtered -> ranking -> ranked.
- [x] each category should be clickable as follows: 
- not ranked to start filtering page. 
- filtering should link to the step that user is last time accepted or  rejected the project
- filtered should link to the [6-D screen ](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1414-5323&t=fIdO0aOfP9TV8nFG-4)
- ranking should link to the step user selected each project before in pairwise comparison page. 
- ranked should link to the screen [7-B Submit Vote](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1414-5976&t=fIdO0aOfP9TV8nFG-4)

- [x] If a user has ended up ranking the more than one category, each time we should load **[Category Comparison Modal](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1681-12596&t=fIdO0aOfP9TV8nFG-4)**  which link user to the [8-C Screen](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2189-5519&t=fIdO0aOfP9TV8nFG-4) and following user flow
- [ ] #51
- [ ] #50

**Comment by MoeNick** [comment]
@mmahdigh @alireza-sharifpour the success criteria was updated.

**Comment by alireza-sharifpour** [comment]
This part is done but it does not have the card view yet.
I'll implement it when all other issues with higher priority are done and we have a full functional app.

@MoeNick @maryjaf

**Comment by maryjaf** [comment]
- [ ] 1-

Based on the ACs, when user taps on a category with “Ranked” status, the “Well done” page should be shown but now the below pic is shown 
![IMG_1625](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/618a872b-1690-46df-9801-3f5b54f096d0)
![IMG_1626](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/a8b26d09-afca-4f05-ae38-f8c436cc5bd5)

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/cd41b72f-873d-4b36-8ef0-bae8c5e0bc56

**Comment by maryjaf** [comment]
> * At header right side,  it should have a connect button for connect flow if user is not connected. if user is already connected, we should show the badges logos, which are clickable to badges guide page.
> * [ ]  At header left side, a random icon of OP should load for every user which SHOULD NOT CHANGE after the registration. the list of[ icons of OP Characters are here](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1399-3596&t=nPvyaLabrEbsywcB-4)

- [ ] 2- 
These 2 ACs aren't ready for testing

**Comment by maryjaf** [comment]
> * [x]  1-
> 
> Based

Now by tapping on a category with "Ranked" status the first pic is shown, is this expected result? 
or second pic should be shown where user could be able to edit the vote again@MoeNick 
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/f54979fe-b2ce-4971-8fc0-d17b51ffb099)

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/c830263b-aed3-47e1-9e3c-bafd6d10c218)

**Comment by MoeNick** [comment]
Ranked means attested, so we assume Pairwise-Ranking-Done & Drag&Drop-Ranking-Done is also ranking state.

**Comment by maryjaf** [comment]
> Ranked means attested, so we assume Pairwise-Ranking-Done & Drag&Drop-Ranking-Done is also ranking state.

I don't get it, the current view is ok ? @MoeNick

**Comment by MoeNick** [comment]
@mmahdigh it needs to be fixed according to today's chat.

**Comment by MoeNick** [comment]
I made the OP character and badges in the header to separate issues. @maryjaf @mmahdigh 
But please check the flow and splash pages between teh flow one more time to make sue the edge cases are working, the we can pass it.

**Comment by MoeNick** [comment]
List view and card view also not checked yet. there was a reason behind it? @maryjaf

**Comment by mmahdigh** [comment]
> @mmahdigh it needs to be fixed according to today's chat.

The state labels have been working according to our discussion since noon yesterday. Let me know if you encounter any bugs there.

**Comment by MoeNick** [comment]
> > Ranked means attested, so we assume Pairwise-Ranking-Done & Drag&Drop-Ranking-Done is also ranking state.
> 
> I don't get it, the current view is ok ? @MoeNick I mean this: Now by tapping on a category with "Ranked" status the first pic is shown, is this expected result?
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/332407348-852b8535-d10d-4768-bb9a-fac8c5aeacf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM4MDIsIm5iZiI6MTcxNjM2MzUwMiwicGF0aCI6Ii8xMTE1MjkxODUvMzMyNDA3MzQ4LTg1MmI4NTM1LWQxMGQtNDc2OC1iYjlhLWZhYzhjNWFlYWNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNzM4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjFhMjUxMTQyYWMxYWY4OTUyNjE5ODhkMTAxN2Y5M2MyZjc2ODYyYzQzMGQ4NTc0NzkyMjM3YTFhNTIwM2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EQyfskMmm2q_2kZyX2rqnqhcmulmRGtgFjNe4MtQOL8)

Please check the latest comment of MaryJaf, @mmahdigh these splash pages only acts as a mediatory between user flows and user should not land on them when starting again from vategory page,

**Comment by MoeNick** [comment]
Sorrry I get your point. 
We want to let the user to edit manualy and attest again if they want, so I think we should show the same screen  with differnt copy. I will get back on this. 
Thanks @maryjaf @mmahdigh
