### ISSUE TITLE
Letting user disconnect from DApp and connect another address / wallet 

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#155]
Basically the `Try a different wallet` buttons should add to those 2 screens. 

<img width="536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21aQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f907fdbd4fceee8f66b2c55bad196204f573e9b/image.png" alt="image.png" />

Design: https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1414-4547&t=pDU6bfkyXUGF3swH-4

**NOTE:** the copies are outdated in above picture please don' change the current copies in app. 

AC:
1. After clicking on 'Try a different wallet`  user should get disconnected and see the collect wallet modal.

**Comment by alireza-sharifpour** [comment]
This PR is ready for testing on Staging @maryjaf

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour the new button "try a different button" works as expected
