### ISSUE TITLE
Category Single Page / Projects List

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#16]
As a user I want to see the projects in a category so I can take a look at the list before i start filtering. 
<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bace5f7694a377dce29590ca33c26b61e8d31a15/image.png" alt="image.png" />

### Success Criteria

- [x]  This screen only show-up once before the first project start, if just one or more projects has been filtered, we should not show this screen.
- [x] Back arrow at the top should show the category list without changing the status. 
- [x] Total projects number should be shown. 
- [ ] Projects should sort alphabetically. 
- [ ] Start buttons and the lower section hovers on the projects list and the rest is scrollable.
- [ ] User should scroll down to the list to make the start button enabled.

**Comment by MoeNick** [comment]
@alireza-sharifpour @mmahdigh success criteria updated on this issue.

**Comment by maryjaf** [comment]
> * [x]   This screen only show-up once before the first project start, if just one or more projects has been filtered, we should not show this screen.
> * [x]  Back arrow at the top should show the category list without changing the status.
> * [x]  Total projects number should be shown.

These success criteria have been passed.

**Comment by maryjaf** [comment]
> > * [x]    This screen only show-up once before the first project start, if just one or more projects has been filtered, we should not show this screen.
> > * [x]   Back arrow at the top should show the category list without changing the status.
> > * [x]   Total projects number should be shown.
> 
> These success criteria have been passed.

could this issue be called as Done? @MoeNick
