### ISSUE TITLE
Mobile | connect with metamask (also on mobile) has some tough issues

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-RPGF4#168]
Does the metamask button on the connect flow work for mobile

On an iphone, the user would try to connect his wallet, which was also on his phone, so he clicked metamask but then metamask said to go back to the app.... and this kept going back and forth... without signing the message

Then he was able to connect by going to metamask's internal browser and navigating to the OTP link and that let him connect.

But then there were 2 matamasks as connect buttons!

<img width="539" alt="Screenshot 2024-06-29 at 12 18 12 AM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/14945613/c3d097f0-4a80-4e90-9b9b-9591c1015545">

**Comment by MoeNick** [comment]
one is MM app and one is browser-injected, we MUST only let walletConnect be active, once user connects it can be seen as a web-injected wallet. 
@alireza-sharifpour has a PR and it will fix that.

**Comment by alireza-sharifpour** [comment]
> one is MM app and one is browser-injected, we MUST only let walletConnect be active, once user connects it can be seen as a web-injected wallet. @alireza-sharifpour has a PR and it will fix that.

Yes, this issue should be fixed.
