### ISSUE TITLE
Copy change, the first screen of a category is confusing

### ISSUE THREAD

**Issue by GriffGreen** [GeneralMagicio/pairwise-RPGF4#169]
<img width="406" alt="Screenshot 2024-06-29 at 12 45 39 AM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/14945613/72cb6006-8e05-47de-a7c1-2bba52b69a90">

When you get to this page, is seems like you should pick 5 projects there... but instead you just need to click the next button

Maybe quick copy change to the red bold text: 

Important: In the next stage, you must select at least 5 projects.

**Comment by MoeNick** [comment]
can you confirm to
