### ISSUE TITLE
[BUG - Staging] By tapping on " Don't connect wallet" nothing happens

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-RPGF4#176]
**Describe the bug**
By tapping on " Don't connect wallet" nothing happens
I've tested on https://app.pairwise.vote and https://staging.app.pairwise.vote

**To Reproduce**
1. Go to 'pairwise app'
2. Click on 'connect'
3. tap on"Don't connect wallet"
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/5fb299e4-bae8-44d2-862b-bc2e6186f140)

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/e54fdabf-4eb9-46ac-9a1b-75a6e081ad4c

**Comment by mmahdigh** [comment]
This is ready for testing.

**Comment by maryjaf** [comment]
Thanks @mmahdigh This issue has been resolved on STG
