### ISSUE TITLE
Filtering Guide

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#18]
As a user I want to understand how filtering projects works. 
<img width="283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0hSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3296fd4c5330d93e4b3b1cb425d8c270cea32d84/image.png" alt="image.png" />

[PLEASE USE THIS LINK ](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-5364&t=nPvyaLabrEbsywcB-4)

**Comment by MoeNick** [comment]
@alireza-sharifpour I updated this issues based on the new design patch. 0.0.2 there's a minor change there.

**Comment by alireza-sharifpour** [comment]
This issue is ready for testing. @maryjaf

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour it has been added but the text of button in figma is"Got it"

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/0fe711f6-457a-403d-aa99-607a70da7a31)

**Comment by MoeNick** [comment]
Just a copy change please @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> Just a copy change please @alireza-sharifpour

Done!
Can you check it again @maryjaf?
