### ISSUE TITLE
UI problem on Cotabe's phone

### ISSUE THREAD

**Issue by Zeptimus** [GeneralMagicio/pairwise-RPGF4#180]
![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/2642bab2-1413-4286-aff9-9e85a3910bae)
![imagen](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/74430951/d2d64081-9f4c-4a0c-9233-7c3ae0acf0b2)

In a few parts of the UI, text doesn't fit that nicely in my device and there is almost no margin space

**Comment by MoeNick** [comment]
Maybe we can improve responsiveness. @lovelgeorge99

**Comment by MoeNick** [comment]
can you review and merge? @mmahdigh

**Comment by maryjaf** [comment]
I haven't seen this issue on my phone, it would be good be checked this with Cotabe after release
