### ISSUE TITLE
New metrics data and applying some feedbacks from Carl

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#188]
The data for metrics that we get was not finally reviewed. Now we need to update the data to a newer version:

https://github.com/opensource-observer/insights/blob/main/analysis/optimism/retrofunding4/data/op_rf4_impact_metrics_by_project.csv

For Testing:
- Lets have the current data dumped somewhere 
- we can compare the new data with older one after this task is done

**Comment by MoeNick** [comment]
We should apply some feedbacks of Carl here as well:

- Remove the log metrics, they aren't useful when you have the linear versions as well

- Turn Trusted Transaction Share into a % (0.142 --> 14%)

- Move OpenRank Trusted Users into UserQuality section

Can you do it @mmahdigh or we should ask @alireza-sharifpour ?

**Comment by MoeNick** [comment]
Any upates on This @mmahdigh ?
I moved it to in-progress.

**Comment by mmahdigh** [comment]
> Any upates on This @mmahdigh ? I moved it to in-progress.

Sure. I'll do it.
