### ISSUE TITLE
Filtering Screen

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#19]
As a user I want to select some projects that I want to put my voting power on them, it helps me to  rank the final short listed projects better, easier and quicker. 
<img width="855" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25SQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d2736c32fc765154367ae5fa7e0beb2177f60f1/image.png" alt="image.png" />
<img width="561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b2c8f9f3f128dc3868d0b337230a36fccde8965/image.png" alt="image.png" />

**[Design Sources here](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7672&t=nPvyaLabrEbsywcB-4)** and [here for success page ](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=1414-5456&t=nPvyaLabrEbsywcB-4)

### Success Criteria:

- [x] User should see the projects page before being able to accept / reject
- [x] undo button shows the previous projects again, and it should edit the last choice
- [x] user can use undo until the first project appear, in this case the undo should be disabled/ disappear. 
- [ ] loading the projects is not ordered, it can be random
- [x] Close button leads user to category list view. letting the category be the "filtering status" 
- [x] Progress bar is based on number of filtered projects. 
- [x] (Preferred ) when the project is selected it the project card has an animation to the right and left. 
- [x] If filtering is done, user can see the summary. 
- [x] in summary screen the selected and not-selected total is shown with an scrollable list. 
- [x] By tapping on start ranking user start the ranking flow. 
- [x] by tapping the back arrow icon in 6-C screen, user will go to the Category List

**Comment by MoeNick** [comment]
@mmahdigh @alireza-sharifpour the success criteria has been updated here.

**Comment by alireza-sharifpour** [comment]
@MoeNick @maryjaf This flow is ready for testing

**Comment by maryjaf** [comment]
- [ ] 1-
I've selected projects of fist category, but after selecting I couldn't keep on the flow  and loading icon was shown
please check below screen record @alireza-sharifpour 

Uploading Screen Recording 2024-05-13 at 4.57.33 PM.mov…

**Comment by maryjaf** [comment]
> * [x]  undo button shows the previous projects again, and it should edit the last choice
> *

- [ ] 2-
when the user tap on undo to check the previous project, should the buttons be disabled again or not ? since in previous step he/she has checked the description  @MoeNick @alireza-sharifpour

**Comment by MoeNick** [comment]
> > * [x]   undo button shows the previous projects again, and it should edit the last choice
> 
> * [ ]  2-
>   when the user tap on undo to check the previous project, should the buttons be disabled again or not ? since in previous step he/she has checked the description  @MoeNick @alireza-sharifpour
> 
>  RPReplay_Final1715607555.mp4

No it's not required @maryjaf to diable the button again.

**Comment by alireza-sharifpour** [comment]
> * [ ]  1-
>   I've selected projects of fist category, but after selecting I couldn't keep on the flow  and loading icon was shown
>   please check below screen record @alireza-sharifpour
> 
>  Screen.Recording.2024-05-13.at.4.57.33.PM.mov

Thanks @maryjaf for testing, can you please go to the Network Tab and Send us the details of the Backend Errors?

CC: @mmahdigh

**Comment by maryjaf** [comment]
> > * [ ]   1-
> >   I've selected projects of fist category, but after selecting I couldn't keep on the flow  and loading icon was shown
> >   please check below screen record @alireza-sharifpour
> > 
> > Screen.Recording.2024-05-13.at.4.57.33.PM.mov
> 
> Thanks @maryjaf for testing, can you please go to the Network Tab and Send us the details of the Backend Errors?
> 
> CC: @mmahdigh

This is happens for category that user selects one or zero project in this category

**Comment by mmahdigh** [comment]
> * [ ]  1-
>   I've selected projects of fist category, but after selecting I couldn't keep on the flow  and loading icon was shown
>   please check below screen record @alireza-sharifpour
> 
>  Screen.Recording.2024-05-13.at.4.57.33.PM.mov 
> actually when The user selects only one project or zero in a category, after completing select project flow , loading icon is shown (I think this comment [#19 (comment)](https://github.com/GeneralMagicio/pairwise-RPGF4/issues/19#issuecomment-2107587971) also related to this )
> 
>  RPReplay_Final1715673067.mp4

This is fixed. Users cannot only select one or zero projects anymore.

**Comment by maryjaf** [comment]
Thanks @mmahdigh this problem has been resolved

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/f688c451-13ed-496a-a79a-29b471b126c7

**Comment by maryjaf** [comment]
> [ ] loading the projects is not ordered, it can be random

could you please tell me more about this AC? @mmahdigh @MoeNick

**Comment by MoeNick** [comment]
It's o @maryjaf let's pass it.
