### ISSUE TITLE
Improvements on submit vote to have the sense of an onchain transaction to users. 

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#191]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEN3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0aecc487b0b3ff83b193c69934a9d83911aebe94/RPReplay_Final1720014507.mov)

Design: https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=5478-7262&t=FgN65KaaimOrpIHf-11

**Comment by MoeNick** [comment]
Can you review and merge @mmahdigh?

**Comment by mmahdigh** [comment]
It's merged and ready to test.

**Comment by MoeNick** [comment]
@maryjaf can you approve it please?

**Comment by maryjaf** [comment]
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/4ad277eb-61df-4643-9b96-6aa8d68603df)
