### ISSUE TITLE
Improve log out visibility

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#192]
With the new design, log out should be in the categories screen fixed at the button. 
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEt2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fee99e634606559daa66980ed7d832f288729c9/image.png" alt="image.png" />

Design Here
https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=5422-29182&t=IdOVTOibDHUjE5AY-11

**Comment by MoeNick** [comment]
In matter of having the report Bug here
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHl3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7748d77c3515dd9ce66f275598d2eb949a8b923a/image.png" alt="image.png" />

https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=4772-15735&t=IrTV1ULJkIEfu3JK-0

**Comment by MoeNick** [comment]
can you review and merge? @mmahdigh

**Comment by mmahdigh** [comment]
It's merged and ready to test.

**Comment by MoeNick** [comment]
@maryjaf can you approve it please?

**Comment by maryjaf** [comment]
It has been fixed.
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/a688dd99-10cc-4916-8a77-98ddbc5e758d)

**Comment by mmahdigh** [comment]
@maryjaf It's also currently present on all screens. I'm not sure if this is intended or not.

![Screenshot 2024-07-08 at 12 32 32 PM](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/46849131/c9cc6c4b-b45b-4151-8d0d-8fa38e56c27c)

**Comment by MoeNick** [comment]
No log-out and Report bug should be only on categories page.

**Comment by maryjaf** [comment]
> But in mobile view, is the design of "report a bug" button fine? @MoeNick

It has been fixed
