### ISSUE TITLE
Countdown on pairwise Dapp

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#207]
The end will be 16th 20:00 cet

![image](https://github.com/user-attachments/assets/b6adc9dc-de2c-4ee5-a9df-683e0bb7f243)

https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=5614-14235&t=wc7xkHQcQEtwaMMv-11

**Comment by MoeNick** [comment]
@maryjaf can you test please?

**Comment by maryjaf** [comment]
It works fine based on the end time 

![image](https://github.com/user-attachments/assets/a1bbc3b9-5a98-4dc0-98bb-7e4bbb00a3c0)

**Comment by mmahdigh** [comment]
@MoeNick shall I merge it to the Prod?
