### ISSUE TITLE
Attest project ranking list in a category. 

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#24]
As a user I want to have an onchain footprint of the ranked listed of projects inside a category. 

### **Success Criteria**

- New Schema for Pairwise ranking project is needs to be defined on EAS, preferably on Sepolia to test easier. 
- Name of the ranked category should have fields in the schema. 
- Comments of the user should have a field in the schema.
- Badge / role of the attester can have a field if it's not break the anonymity. 
- Proofs for connect (delegation) and proofs for calculations on each attestation should have a field in the schema. The Goal is to prove we’re honest.
- No weights, no percentages, and no OP amounts  just a sorted list, it can be on IPFS but for for using Subquid Service
I suggest having the ranked projects as an array in a field of the Schema. 
- Attestation will be made by the smart wallet address, anon.
- For each user's badge we should do a separate attestation. 
- User should have the Op-eth in their wallet to be able to do the attestation, for managing the gas amount we should have separate issue. 
- in UI we show a success and we will do the attestations in background. So if any of these attestations failed, we should retry and be able to monitor. 
- We should revoke the latest attestation, if the user make a new one for the SAME CATEGORY. this should also be monitored.

**Comment by MoeNick** [comment]
@jainkrati @mmahdigh 
This is a issue  is sort of mutual with your currant tasks, as @mmahdigh is going to use the old-schema and it might affected by the success criteria. So just mentioned you both here to decide.

**Comment by jainkrati** [comment]
@mmahdigh pls take this up as we discussed last week

**Comment by mmahdigh** [comment]
This is testable. However, due to Bandada integration still pending, we currently only satisfy these ACs.

> - New Schema for Pairwise CATEGORY RANKING needs to be defined on EAS, preferably on Sepolia to test easier.
> - Name of the ranked category should have fields in the schema.
> - Comments of the user should have a field in the schema.
> - Attestation will be made by the smart wallet address, anon.
> - User should have the Op-eth in their wallet to be able to do the attestation, for managing the gas amount we should have separate issue.
> - in UI we show a success and we will do the attestations in background. So if any of these attestations failed, we should retry and be able to monitor.

You can check your browser's console to see the attestation id. Here's the [schema](https://optimism-sepolia.easscan.org/schema/view/0x3e3e2172aebb902cf7aa6e1820809c5b469af139e7a4265442b1c22b97c6b2a5) for now.

**Comment by MoeNick** [comment]
Thanks @mmahdigh 
I'd
- Name the schema to paiwise projects ranking with pairwise logo
- remove the pinata file and add a ranking number to projects IDs, https://giveth.mypinata.cloud/ipfs/QmWboQhXrBCjWZgn1Us5Wvgxc1Wy9TQCFRm8Rap4ZUkhWa 
- Also the comments should be there that I can't see it as you said it's in AC
- The idea of retrying is something we should thnk about how to test. 
- I can't get the listname=root in some attestations like https://optimism-sepolia.easscan.org/attestation/view/0x7eed083a8c2fa456eaca81e158213378ea586ef5a2bdf5337b9caf715c4c00ee

**Comment by mmahdigh** [comment]
> Name the schema to paiwise projects ranking with pairwise logo

I'm not sure if we can name the schemas on EAS?

> remove the pinata file and add a ranking number to projects IDs,

For this, let's wait to see how these attestations are going to be consumed. Then we can modify as needed.

> Also the comments should be there that I can't see it as you said it's in AC

The comment is in the `listDescription` field of the Pinata object

> The idea of retrying is something we should thnk about how to test.

Currently, we don't redirect the user to the done page as long as the attestation transaction is not confirmed. We can improve the error handling in later iterations. 

>  I can't get the listname=root in some attestations

That's a mistake on my part. I'm calling category ranking attestation list names "root", an artifact of the previous version. Will change it to "Pairiwse categories" or anything else you might have in mind?

**Comment by MoeNick** [comment]
- [ ] We can name the like : https://optimism.easscan.org/schema/view/0x401a80196f3805c57b00482ae2b575a9f270562b6b6de7711af9837f08fa0faf pls lemme know what you need.
- [ ] No one consume it unless us, so foe cacluation I'd say lets sync with @jainkrati , I guess haveing them on the attestation field helps us better to calculate the weigh of vote. 
- [ ] We should get the list of needed attestation in backend and show the done, this is required as the nu,ber of attestation will be too much for the user to wait. 
- [ ] Is it possible we have the comment in attestation? 
- [ ] Category ranking needs another schema as we have issue for it. so no root please. 
- [ ] @mmahdigh

**Comment by maryjaf** [comment]
- [ ] It seems when user has completed project ranking and before submit vote,  if  user changes the ordering of project, this changes won't be applied in attestation

in below attestation I changed the rank of    "name": "IC3" :  "RPGF3_Application_UID": "0xb8741b55dc416bd673cfb40a1ae2f19e10e1ddc2acc809c27016a5a4c17484fa" 
from positisin 7 into 1, but in attestation it is shown in position 7 

@mmahdigh

**Comment by maryjaf** [comment]
> * [x]  It seems when user has completed project ranking and before submit vote,  if  user changes the ordering of project, this changes won't be applied in attestation
> 
> in below attestation I changed the rank of "name": "IC3" : "RPGF3_Application_UID": "0xb8741b55dc416bd673cfb40a1ae2f19e10e1ddc2acc809c27016a5a4c17484fa" from positisin 7 into 1, but in attestation it is shown in position 7 https://optimism-sepolia.easscan.org/attestation/view/0x0ed558201e29beb695ed332bf3c5e07404307975ec7303980fcc3ee6592a3bd3
> 
> https://giveth.mypinata.cloud/ipfs/QmTyb3wS5wnE8bMsBjAiSM9XAdEzRF67y7oEWDS8ciEmxW @mmahdigh

in new edit flow this problem has been fixed
