### ISSUE TITLE
Preview and EDIT the ranked projects

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#25]
As a user I want to see the  result of pairwise ranking and edit the results if the  ranking was not seems ok.
<img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFhTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0885718cb70ffeb8511dd28b74c1babc00da41a9/image.png" alt="image.png" />

### **Success Criteria**

- [x] Ranking will be created based on the budget-box algo in background.
- [x] Projects ranked based on top % to the lowest. 
- [x] we should keep the % in backend as the latest votes of a user. 
- [x] user can drag and drop the result to change the ranking
- [x] By clicking on Submit vote, user can see the Submit Vote screen anc can add comment to the rankings he's making for taht specific category. 
- [x] if description is less than 100 characters, and click on submit vote, the "Min 100 Character" will be red to take the user's attention.

**Comment by MoeNick** [comment]
@mmahdigh @alireza-sharifpour the success criteria is updated.

**Comment by alireza-sharifpour** [comment]
The FE of this issue is done and the user also can sort and send to the backend.
The add comment part is not completed yet. Only the UI is done and connected to backend.

@MoeNick @maryjaf

**Comment by maryjaf** [comment]
- [ ] 1-
I’ve got an error after submit voting
Please take a look @mmahdigh 


https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/4f89167e-70cf-433d-9516-52d4529140a5

- [ ] 2-
as @MoeNick's comment the minimum character should be 200 and the user couldn't be able  to submit when he/she describes  in lower than 200 character  
![IMG_1632](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/b8896edd-8dd2-46b1-bee1-82a92135ce14)

**Comment by maryjaf** [comment]
- [ ] 1-
based on @MoeNick 's comment in the last step of this flow, setting comment and submit vote,
the comment should be more than 200 character and it should be required @MoeNick @alireza-sharifpour 
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/82ccd2a0-e621-4577-901e-2ff66967abc1)

**Comment by maryjaf** [comment]
> * [ ]  Ranking will be created based on the budget-box algo in background.
> * [ ]  we should keep the % in backend as the latest votes of a user.

- [ ] 2-

These 2 items aren't testable now

**Comment by mmahdigh** [comment]
> * [ ]  1-
>   based on @MoeNick 's comment in the last step of this flow, setting comment and submit vote,
>   the comment should be more than 200 character and it should be required @MoeNick @alireza-sharifpour
>   ![image](https://private-user-images.githubusercontent.com/111529185/330805566-82ccd2a0-e621-4577-901e-2ff66967abc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDUwMDcsIm5iZiI6MTcxNjIwNDcwNywicGF0aCI6Ii8xMTE1MjkxODUvMzMwODA1NTY2LTgyY2NkMmEwLWU2MjEtNDU3Ny05MDFlLTJmZjY2OTY3YWJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMTMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTUzM2ZlYTMyYmY3YTk3NTBjMjkxZGFkMDhhMGVkNTQ5OGRhODFlN2I5YTU2ZWU0ZTkzNWUxNjNiOGNjZDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4iKBFG6XKzo2g-2PZstGH8-aws8ph8qH9Fi7ZVLkM-Q)

This works correctly now. Please retest it.
