### ISSUE TITLE
Desktop connect flow | Landing Page

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#27]
<img width="624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekhTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6842e414bc50397c93ffa39fcf63a077e182bb67/image.png" alt="image.png" />

Design: https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7688&t=nPvyaLabrEbsywcB-4

**Comment by MoeNick** [comment]
@Zeptimus any updated from video? dev team started implementing this.

**Comment by MoeNick** [comment]
@alireza-sharifpour 
- X page: https://twitter.com/Pairwisevote
- GitHub: https://github.com/GeneralMagicio/pairwise-RPGF4
- Please remove discord and docs
- Blog (Paragraph) https://github.com/GeneralMagicio/pairwise-RPGF4

**Comment by MoeNick** [comment]
@alireza-sharifpour thi issues is updated. I remove my assignee here.

**Comment by maryjaf** [comment]
https://github.com/GeneralMagicio/pairwise-RPGF4/issues/28#issuecomment-2133400637

**Comment by MoeNick** [comment]
it's ok for now
