### ISSUE TITLE
Desktop connect flow | Connect Wallet and check the voting power

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#28]
As a user I want to connect my wallet to the desktop panel and see my badges. 
<<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a51cfc96c78e60751704e84ac6940ddeac19f2dc/image.png" alt="image.png" />

- There will be no extra step for claiming the badges. 
- At the same screen user can put the OTP.

**Comment by MoeNick** [comment]
As @alireza-sharifpour said the  UI  is ready. 

CC: @jainkrati

**Comment by maryjaf** [comment]
I haven't seen "connect wallet" on the main page "https://pairwise-rpgf-4.vercel.app/"
and could you please add more data about test of this issue @alireza-sharifpour @MoeNick 

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/499b96d1-9bce-48d6-a3af-345f2e30723d)

**Comment by MoeNick** [comment]
@maryjaf 
- User will go to https://pairwise-rpgf-4.vercel.app/connect
- See a landing page like [This Screen](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7797&t=cDIz6KajZwbF2xGA-4)
- user connects wallet and sees [this screen](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7947&t=cDIz6KajZwbF2xGA-4)

**Comment by MoeNick** [comment]
> I haven't seen "connect wallet" on the main page "https://pairwise-rpgf-4.vercel.app/" and could you please add more data about test of this issue, I did not understand it properly @MoeNick @alireza-sharifpour
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/333889179-499b96d1-9bce-48d6-a3af-345f2e30723d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzY0NjgsIm5iZiI6MTcxNjczNjE2OCwicGF0aCI6Ii8xMTE1MjkxODUvMzMzODg5MTc5LTQ5OWI5NmQxLTliY2UtNDhkNi1hM2FmLTM0NWYyZTMwNzIzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNTA5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTNhNGUyZmQ1ODZjMTIwY2QzNmMyNmQ5OThmNWFhZmYxOGM1NjY1YzE0Nzc1ODY5NzFjMzE5MDgyYWZlN2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._bFYld3tHm9zP5-z4nW9rYxfpgL59RwPj6uJeKvL6-I)

That happens due to a bug that on this route we check login by web2 that should be removed.

**Comment by maryjaf** [comment]
> * See a landing page like [This Screen](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7797&t=cDIz6KajZwbF2xGA-4)

Based on figma, there is a video that it hasn't been added in the below page

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/6a634c0d-6c33-41a2-8a56-900f14b4f3d3)

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/12059401-2feb-4e0d-b242-89d3ecba4971)

**Comment by maryjaf** [comment]
> * user connects wallet and sees [this screen](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7947&t=cDIz6KajZwbF2xGA-4)

By tapping on "How to get OTP?" nothing happens

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/51221aa7-c246-4280-a1d7-d05b8775268c)

**Comment by MoeNick** [comment]
> > * user connects wallet and sees [this screen](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7947&t=cDIz6KajZwbF2xGA-4)
> 
> By tapping on "How to get OTP?" nothing happens
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/334104779-51221aa7-c246-4280-a1d7-d05b8775268c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjIwMTAsIm5iZiI6MTcxNjgyMTcxMCwicGF0aCI6Ii8xMTE1MjkxODUvMzM0MTA0Nzc5LTUxMjIxYWE3LWMyNDYtNDI4MC1hMWQ3LWQwNWI4Nzc1MjY4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNDU1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWRjOTk0YzEyOGRmNjIyZjBiYmI5NmM2YzkyZGM2ODZhY2NmYzczYjZlZjQ4NjU3NDBiZGFmZGVlYzJhMjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f1B6FoAiCPcv0dQ4-CuCw-lv5qVUIHd3ovVutNfmNdc)

This How to is on me! 
I will update a text to show it as tooltip.

**Comment by MoeNick** [comment]
> > * See a landing page like [This Screen](https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=2266-7797&t=cDIz6KajZwbF2xGA-4)
> 
> Based on figma, there is a video that it hasn't been added in the below page
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/334103962-6a634c0d-6c33-41a2-8a56-900f14b4f3d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjI5NzcsIm5iZiI6MTcxNzA2MjY3NywicGF0aCI6Ii8xMTE1MjkxODUvMzM0MTAzOTYyLTZhNjM0YzBkLTZjMzMtNDFhMi04YTU2LTkwMGYxNGI0ZjNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwOTUxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWYxMmIwNDRkNDNhODM1ZDAxMTI5ZjliNzQzZmE3MjFhODE4MDIzZmY0NDIwZWZiNWQxMzQzNDhmYzhkMjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P0jech5JwRY026FuCVgDob3ZZRw5eKQ6aMw_yVNxZ7o)
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/334104309-12059401-2feb-4e0d-b242-89d3ecba4971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjI5NzcsIm5iZiI6MTcxNzA2MjY3NywicGF0aCI6Ii8xMTE1MjkxODUvMzM0MTA0MzA5LTEyMDU5NDAxLTJmZWItNGUwZC1iMjQyLTg5ZDNlY2JhNDk3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwOTUxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODFiYzlkOTgzNWJhOTk5ODM1YWUxYjBlNDlmOTZiNDNmYWI0NzdjMTI1MGY5NzU4YmQ1NjRkNjFlYTc3MDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rX4-Hy_4QS380dmZU8pOVSGsZLYEl1NBtyfilXTcpAo)

@maryjaf first screen issue is here: https://github.com/GeneralMagicio/pairwise-RPGF4/issues/27 not in this issue.

**Comment by maryjaf** [comment]
- Item 1 & 2 haven't been fixed yet. @alireza-sharifpour 

- [ ] 3- please take a look on below screen record
- I  connect my wallet
- I'm redirect to https://pairwise-rpgf-4.vercel.app/connect/otp
-by tapping on back icon I see this page https://pairwise-rpgf-4.vercel.app/connect, but I can't scroll in this page 

@alireza-sharifpour @MoeNick

**Comment by mmahdigh** [comment]
[1] & [2] is pending assets from the product team. (cc: @MoeNick)
[3] I can't see any screen records in your comment. @maryjaf

**Comment by maryjaf** [comment]
> [3] I can't see any screen records in your comment. @maryjaf


https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/ccee699a-a979-4b49-967f-350ec11f8fd6

**Comment by mmahdigh** [comment]
> > [3] I can't see any screen records in your comment. @maryjaf
> 
>  Screen.Recording.2024-06-11.at.4.49.44.PM.mov

This is fixed now. Added a button instead of automatic redirects.

**Comment by maryjaf** [comment]
> [1] & [2] is pending assets from the product team. @maryjaf

@MoeNick kindly reminder

**Comment by MoeNick** [comment]
Tooltip for "How to get OTP?"
`Go to the Pairwise WebApp and click on connect. You'll get the code. Use it here if you don't have your wallet on the other device`

@maryjaf @alireza-sharifpour

**Comment by mmahdigh** [comment]
This is ready for retesting. @MoeNick

**Comment by maryjaf** [comment]
> Tooltip for "How to get OTP?" `Go to the Pairwise WebApp and click on connect. You'll get the code. Use it here if you don't have your wallet on the other device`
> 
> @maryjaf @alireza-sharifpour

I couldn't see the tooltip
https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/44643a5a-2d58-4ad8-aee5-5b75372aebe1

@mmahdigh

**Comment by mmahdigh** [comment]
> > Tooltip for "How to get OTP?" `Go to the Pairwise WebApp and click on connect. You'll get the code. Use it here if you don't have your wallet on the other device`
> > @maryjaf @alireza-sharifpour
> 
> I couldn't see the tooltip https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/44643a5a-2d58-4ad8-aee5-5b75372aebe1
> 
> @mmahdigh

Could you retest this again while waiting at least 2 seconds?
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/46849131/665f1364-7ceb-424d-b1e7-41dae0e55f4a)

**Comment by MoeNick** [comment]
Shall we test with auto inserted OTP from url params? @mmahdigh?

**Comment by mmahdigh** [comment]
> Shall we test with auto inserted OTP from url params? @mmahdigh?

Yes.
