### ISSUE TITLE
Desktop connect flow | Success Page

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#30]
Just a success screen. 
<img width="847" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEhTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--741b7b49518dfdb932566873abc983633b04c32e/image.png" alt="image.png" />

**Comment by MoeNick** [comment]
As @alireza-sharifpour said the  UI  is ready. 

CC: @jainkrati

**Comment by maryjaf** [comment]
- [ ] "Find out how this zk-proof delegation works" isn't clickable 

<img width="1566" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0feae0c24cc9b33fdabff19e1ff92b16a44a5aac/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
[ ] 2- I'm not sure this problem is exactly related to this issue or not @MoeNick please tell me if I wrong 

-I tap on to connect wallet in desktop flow (https://pairwise-rpgf-4.vercel.app/categories)
-I my wallet address has no badge 
-after completing sign flow in metamask , I see the below error 

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/b1efc092-b6f8-457c-8b8c-704177cfed2c)

[Screen Recording 2024-06-10 at 11.47.55 AM.zip](https://github.com/user-attachments/files/15758986/Screen.Recording.2024-06-10.at.11.47.55.AM.zip)
@mmahdigh

**Comment by mmahdigh** [comment]
@maryjaf [1] is pending a link from the product team. (cc: @MoeNick)
[2] This is solved. Addresses with no badges are not allowed to proceed further.

**Comment by maryjaf** [comment]
> * [x]   2- I'm not sure this problem is exactly related to this issue or not @MoeNick please tell me if I wrong
> 
> -I tap on to connect wallet in desktop flow (https://pairwise-rpgf-4.vercel.app/categories) -My wallet address has no badge -after completing sign flow in metamask , I see the below error
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/338104361-b1efc092-b6f8-457c-8b8c-704177cfed2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTA1ODEsIm5iZiI6MTcxODExMDI4MSwicGF0aCI6Ii8xMTE1MjkxODUvMzM4MTA0MzYxLWIxZWZjMDkyLWI2ZjgtNDU3Yy04YjhjLTcwNDE3N2NmZWQyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMjUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDgyNDM3ZDc5NzMzMTczYTUzOWJiZDk3MDE3ODRjMDdjNDA0OWUwZGJlZjBhZTFkMjRhN2I0ZDlkNDMxODc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NWkk5mbg8jG_rjXuNfIbKg3etbHUkq_cP5xZULZ9gVM)
> 
> ______-
> 
> [Screen Recording 2024-06-10 at 11.47.55 AM.zip](https://github.com/user-attachments/files/15758986/Screen.Recording.2024-06-10.at.11.47.55.AM.zip) @mmahdigh

Thanks @mmahdigh It has been fixed

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/966ec460-a625-4994-883e-ec01d000c257)

**Comment by maryjaf** [comment]
- [ ] 3- 
in desktop flow, where there is a problem for connecting a wallet address for example: This eth address is already connected
this message isn't shown in UI and the users see "loading" in this modal

 
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/ce144d5b-47c8-4941-9410-c39ff266dc17)

**Comment by MoeNick** [comment]
Any updates on this? 
@alireza-sharifpour @mmahdigh

**Comment by mmahdigh** [comment]
> Any updates on this? @alireza-sharifpour @mmahdigh

Yes. Added a generic error state.

**Comment by MoeNick** [comment]
Can you re-test @maryjaf?

**Comment by maryjaf** [comment]
I've tested and now for all negative scenarios  a same message is shown

**Comment by MoeNick** [comment]
I need to update the link of how zk-game is working in this screen, lets' keep it here
