### ISSUE TITLE
Welcome and get started

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#31]
As a user I want to see a short introduction after I signed in for the first time. 
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0846e2a18ff7d6d07d06bf7520b85d75bc813e24/image.png" alt="image.png" />

Success Criteria:
- It shows only once after sign up, so if user logs in for second time they will see categories list page not this page. 

**Design Assets:**
https://www.figma.com/file/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?type=design&node-id=1373-11010&mode=design&t=eJAHaFIo1rVACUI9-4

**Comment by MoeNick** [comment]
@mmahdigh @alireza-sharifpour success criteria's updated.

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf @MoeNick

**Comment by maryjaf** [comment]
- [ ] 

I've logged in with my gmail and completed some flow and ranked the projects but like as below video I see this introduction again

**Comment by mmahdigh** [comment]
> * [ ]
> 
> I've logged in with my gmail and completed some flow and ranked the projects but like as below video I see this introduction again
> 
>  RPReplay_Final1715608272.mp4

This is also fixed. Please give it another try.

**Comment by maryjaf** [comment]
This issue has been solved.
