### ISSUE TITLE
Image Placeholder for projects

### ISSUE THREAD

**Issue by alireza-sharifpour** [GeneralMagicio/pairwise-RPGF4#34]
Discussed it with Ayaz and we decided to use a background and show the project name on top.

**Comment by MoeNick** [comment]
please add the epic @alireza-sharifpour 
if it's needed in MVP please let me know to put priorities on.

**Comment by MoeNick** [comment]
@alireza-sharifpour kindly reminder

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf

**Comment by maryjaf** [comment]
<img width="1363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5edd836b4dd918cb02811c581d9f1184ef1fdc0/image.png" alt="image.png" />
