### ISSUE TITLE
Set up PostHog for MVP

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#46]
@mosaeedi created the account. 

https://posthog.com/docs/libraries/js

Funnel rough:
- Landing page
- login page
- logged in and landed in categories page
- connect from landing page. 
- Filtered
- Ranked
- Attested
- Category comparison
- attest between categories.

**Comment by mosaeedi** [comment]
I'll update this issue by Tuesday this week!

**Comment by mosaeedi** [comment]
## Installing PostHog

You can find the guides to install PostHog on the project here -> [Link to PostHog Doc](https://posthog.com/docs/getting-started/install?tab=sdks)

NOTE: You will need an API key, I'm not sure if I can just paste it here, whoever wants to install it can reach out to me for the API Key!

## Setup Auto capture

We need to set up the PostHog Auto capture feature to ensure the session recording is working.
Find the Docs here -> [Link to PostHog doc](https://posthog.com/docs/getting-started/send-events#1-setup-autocapture)


## Send custom events
We have to send some custom events to set up more precise Funnels!
For sending custom events -> [Link to PostHog Doc](https://posthog.com/docs/getting-started/send-events#2-capture-custom-events)

For each of these steps, we need to send a custom event.


### 1. Landing page
**Event name:** `Just landed`

### 2. Login page
**Event name:** `Opened Login Page`

### 3. Logged in 
**Event name:** `User Logged In`
**Custom properties:** `Login by:` _Login Method_

### 4. Landed in the categories page
**Event name:** `User goes to the Categories page`
**Custom properties:** `Category:` _Name of the category they have selected_

### 5. connect from the landing page.
!!!

### 6. Filtered
**Event name:** `Filtered`
**Custom properties:**
`categories:` _List of the categories they've Filtered_
`Attempts:` _ex: First time_

### 7. Ranked
**Event name:** `Ranked`
`categories:` _List of the categories they've Ranked_


### 8. Attested
**Event name:** `Attested`
**Custom properties:**
`categories:` _List of the categories they've Attested_


### 9. Category comparison
**Event name:** `Comparing categories`
**Custom properties:**
`categories:` _Categories they are comparing_


### 10. Attest between categories.
**Event name:** `Attested between categories`
**Custom properties:**
`categories:` _Categories they are attesting to_

**Comment by ahmadabugosh** [comment]
hey @jainkrati  @mmahdigh @mosaeedi, Can we start with steps 1 and 2? Those are just a few lines of code and shouldn't require much work for us to at least get basic analytics (if we need step 3 later on we can worry about it later).

**Comment by MoeNick** [comment]
Spending an hour on this for thses 2 first issues.

**Comment by ahmadabugosh** [comment]
@MoeNick Are there any blockers on this?

**Comment by mosaeedi** [comment]
For Pairwise, we are using the EU servers from PostHog,
So to be able to connect to the PostHog account we need to use `eu.posthog` domain,
Right now, Pairwise is trying to connect to `us.posthog` and return an error.


<img width="569" alt="Screenshot 2024-06-23 at 2 19 13 PM" src="https://github.com/GeneralMagicio/pairwise-RPGF4/assets/13708322/799f1156-6aa1-4ec0-bd3b-639064d84b6c">

**Comment by MoeNick** [comment]
Tagging @mmahdigh @lovelgeorge99 to fix

**Comment by lovelgeorge99** [comment]
@mmahdigh you just need to change the environment variable for POST_HOG_HOST to https://eu.i.posthog.com

**Comment by mmahdigh** [comment]
Done. Ready for retesting. @mosaeedi @MoeNick

**Comment by mosaeedi** [comment]
It's working!
You can close this issue if you need.
