### ISSUE TITLE
Metrics | Pairwise comparison flow changes.

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#56]
<img width="662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2IvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f77d955529a66b9c54d09c6c504c75008ccfa88a/image.png" alt="image.png" />

### Acceptance Criteria: 

- [x] Header and Progress bar is fixed.
- [x] 2 buttons for comparison at the bottom, with logo and title
- [x] the bottom logos are clickable.
- [ ] the bottom logos are hovering when user scrolls
- [x]  projects will have some main metrics and some sub metrics as follows, before the round we may have some more or less metrics that will be done in #62 issue.
- [ ]  Every sub-metric will have a value as number and a unit.
- [ ]  unit will be none/ gWei / % / $ 
- [x]  if a metric number value is more  than 3 character, we should show K, M.
- [ ]  The better value will be green.  We should have a filed to demonstrate less is better or more is better to detect the greenness of these fields. 
- [ ]  if user  hit the threshold, we should show a `finish ranking button` button with fixed width. 
- [ ]  Adding new fileds added to schema. You can find the f[inal schema here ](https://drive.google.com/file/d/1ZU7SCDzbHISWAork5fiHjXKv_ENS0hri/view?usp=sharing)

**Comment by maryjaf** [comment]
> * The better value will be green.  We should have a filed to demonstrate less is better or more is better to detect the greenness of these fields.

- [ ] 1- I couldn't find this field  to demonstrate less is better or more is better @alireza-sharifpour 

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/346f1576-7af7-41a5-a167-ee78bfe8e5aa)

**Comment by alireza-sharifpour** [comment]
Finish ranking button is removed.
I couldn't find less is better or more is better in the design.
@maryjaf @MoeNick

**Comment by MoeNick** [comment]
> > * The better value will be green.  We should have a filed to demonstrate less is better or more is better to detect the greenness of these fields.
> 
> * [ ]  1- I couldn't find this field  to demonstrate less is better or more is better @alireza-sharifpour
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/339366733-346f1576-7af7-41a5-a167-ee78bfe8e5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDAzNTMsIm5iZiI6MTcxODcwMDA1MywicGF0aCI6Ii8xMTE1MjkxODUvMzM5MzY2NzMzLTM0NmYxNTc2LTdhZjctNDFhNS1hMTY3LWVlNzhiZmU4ZTVhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwODQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGM2NTRlZTc1ODcwYzczNmE2MzliNGYyMzcyNDQwMjc3ZDMxNTMwYzY2YjZiMWI1NzQ3YzIyZTc1NTYzYzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G5uguCVMzlcChqAQ6ilaX8cXNNBYPIBdEBOAI4AcRmU)
> 
> > * if user  hit the threshold, we should show a `finish ranking button` button with fixed width.
> 
> * [ ]  2-In my tests I have to compare all the projects and I haven't seen the finish ranking button

For 2, The flow has been changed and on threshold (not all possible comparisons) user will get redirected to result page. So it's fine.  @alireza-sharifpour @maryjaf

**Comment by MoeNick** [comment]
I will add more items with @maryjaf permission :D
- [ ] 3-  The units are missing here as well, we have gWei fro gas, and we may have $ for some fields later
- [ ] 4- the width of buttons below should be the same. I mean if a project needs less width, increase it to max. Preferably for all comparisons we should have fix width so users get used to it. 
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/80677512/b0dd1516-be32-40b5-896e-d799b48a98da)

**Comment by alireza-sharifpour** [comment]
I'll add all the things you mentioned and update the issue.

**Comment by MoeNick** [comment]
@alireza-sharifpour
I added the new schema as an item to this issue, please let @maryjaf know when to test. 
Thanks

**Comment by MoeNick** [comment]
@maryjaf @alireza-sharifpour I put this to test column again.

**Comment by maryjaf** [comment]
if it isn't ready for testing please move it back into inprogress

**Comment by maryjaf** [comment]
this copy should be changed ? @alireza-sharifpour 
<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9453b725f0efb696f8b9158b01dbaf5293617bd/image.png" alt="image.png" />

New design:

<img width="438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk9TQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92aa9e695ac5d90f6f81e275af3c36198b3d550f/image.png" alt="image.png" />
