### ISSUE TITLE
Data |  Snapshots of weights for OP holders, badge holders, recipients and delegates

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#60]
Buckets:
https://docs.google.com/spreadsheets/d/1rxipvXwbTZiqOc5CNvqXSIF_zDcYZsa9IHrF19qQsWk/edit#gid=27201902

 would propose that if you are a badgeholder, you can also be an OP token holder.

If you are a Delegate, you can be nothing else, and if you are a badgeholder, you are not a delegate.

If you are a Recipient you can also be an OP token holder, but if your recipient address is a Badgeholder or a Delegate, then you do not count as a Recipient.
Said another way, Recipients and Badgeholders get their votes counted as OP token holders as well.

The 20 badgeholders that are also delegates are excluded from being delegates.

**Comment by MoeNick** [comment]
[Points RPGF-Snapshot Sample _TypeAmontIndcluded.json](https://github.com/user-attachments/files/15753678/Points.RPGF-Snapshot.Sample._TypeAmontIndcluded.json)

@alireza-sharifpour I changed the file and added the Types and Amounts. 
FYI: @mmahdigh

**Comment by MoeNick** [comment]
Th only remained item is decition makimg over the delagates to be users

**Comment by MoeNick** [comment]
OK 
On the last call, we decided to add more recipient addresses when the Agora API opens up. I asked @lovelgeorge99 to jump into this one: 

**What to do:**

- Search for all team members of projects
- find their farcaster id
- find their addresses on farcaster

Once done, we should exclude the the addresses we already have in CSV, and add new once to the csv with their fields:
- Amount
- Type
_ Weights

**Comment by MoeNick** [comment]
Changes:

- [ ] New recipient lists based on project users added
- [ ] Test projects has been removed from the recipients list 

@mmahdigh do you have any idea how to test? 
Is it done

**Comment by mmahdigh** [comment]
> Changes:
> 
> * [ ]  New recipient lists based on project users added
> * [ ]  Test projects has been removed from the recipients list
> 
> @mmahdigh do you have any idea how to test?

The last snapshot file is up on Staging. Regarding how to test, I don't really have any idea honestly. But let's test if the connect-related functionalities are working and we have no regression bugs.

**Comment by MoeNick** [comment]
@maryjaf to test if the connect-related functionalities are working and we have no regression bugs.

**Comment by maryjaf** [comment]
> @maryjaf to test if the connect-related functionalities are working and we have no regression bugs.

I haven't seen any new problem in connect flow

**Comment by MoeNick** [comment]
Shall we apply  new / removed recipient addresses to production? @mmahdigh

**Comment by mmahdigh** [comment]
> Shall we apply new / removed recipient addresses to production? @mmahdigh

Sure.

**Comment by mmahdigh** [comment]
It's deployed and ready to use on Production.
