### ISSUE TITLE
Editing Ranked Category

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#68]
Currently for attested categories  (RANKED) we show this message to users, and the can only get back to the categories page. 

<img width="302" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--637130d03577b609a030d1978ea94e5b8f9572e8/image.png" alt="image.png" />

This should change to this:
<img width="569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9a7354cda74bde640b81059d501c40a176c1d86/image.png" alt="image.png" />

Design is here: https://www.figma.com/design/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?node-id=3687-4021&t=wibb9gouQjdt4JSk-4

**Comment by MoeNick** [comment]
@mmahdigh @alireza-sharifpour I updated the design for this issue,

**Comment by MoeNick** [comment]
Thursday Morning by @alireza

**Comment by maryjaf** [comment]
- [ ] 1-
- the user taps on edit vote
- the user doesn't change any item
- the user taps on "discard changes"
- in this case that the user does no change in  the ranking, he has to submit again the vote
@mmahdigh 

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/dc574317-f56a-4f63-8374-dc2f38cba0a5

**Comment by mmahdigh** [comment]
> * [ ]  1-
> * the user taps on edit vote
> * the user doesn't change any item
> * the user taps on "discard changes"
> * in this case that the user does no change in  the ranking, he has to submit again the vote
>   @mmahdigh
> 
>  Screen.Recording.2024-06-18.at.4.59.29.PM.mov

This is more of a design issue. We can put a button directing to the categories screen there.

**Comment by MoeNick** [comment]
So we can do the attestation one more time and we revoke the last time attestation. This was my assumption. right? @mmahdigh

**Comment by mmahdigh** [comment]
> So we can do the attestation one more time and we revoke the last time attestation. This was my assumption. right? @mmahdigh

Yes.

**Comment by MoeNick** [comment]
Let's move it to done then

**Comment by MoeNick** [comment]
@maryjaf to test the revoked attestation for the category that has been ranked before.

**Comment by maryjaf** [comment]
> @maryjaf to test the revoked attestation for the category that has been ranked before.

I'm not sure I get your point or not
when I ranked a new category , the previous attestation of categories should be changed to revoked? @MoeNick 

for both of these attestations the "REVOKED" is : No 
but it seems based on @MoeNick  comment,  the older attestation should be revoked 

https://optimism-sepolia.easscan.org/attestation/view/0x7f656d92f15ff1d19fbee8a70bfc4f1279521a1e1f0b3c0403721579ab741eeb

https://optimism-sepolia.easscan.org/attestation/view/0x951e2ebcd00e2c4de20eee12db809400ef22e0df7c4369338d58d17b3dad69a5

@mmahdigh

**Comment by mmahdigh** [comment]
> > @maryjaf to test the revoked attestation for the category that has been ranked before.
> 
> I'm not sure I get your point or not when I ranked a new category , the previous attestation of categories should be changed to revoked? @MoeNick
> 
> for both of these attestations the "REVOKED" is : No but it seems based on @MoeNick comment, the older attestation should be revoked
> 
> https://optimism-sepolia.easscan.org/attestation/view/0x7f656d92f15ff1d19fbee8a70bfc4f1279521a1e1f0b3c0403721579ab741eeb
> 
> https://optimism-sepolia.easscan.org/attestation/view/0x951e2ebcd00e2c4de20eee12db809400ef22e0df7c4369338d58d17b3dad69a5
> 
> @mmahdigh

These two attestations have different attesters though?

**Comment by maryjaf** [comment]
> > > @maryjaf to test the revoked attestation for the category that has been ranked before.
> > 
> > 
> > I'm not sure I get your point or not when I ranked a new category , the previous attestation of categories should be changed to revoked? @MoeNick
> > for both of these attestations the "REVOKED" is : No but it seems based on @MoeNick comment, the older attestation should be revoked
> > https://optimism-sepolia.easscan.org/attestation/view/0x7f656d92f15ff1d19fbee8a70bfc4f1279521a1e1f0b3c0403721579ab741eeb
> > https://optimism-sepolia.easscan.org/attestation/view/0x951e2ebcd00e2c4de20eee12db809400ef22e0df7c4369338d58d17b3dad69a5
> > @mmahdigh
> 
> These two attestations have different attesters though?

Yeah it's my mistake

**Comment by maryjaf** [comment]
> > > @maryjaf to test the revoked attestation for the category that has been ranked before.
> > 
> > 
> > I'm not sure I get your point or not when I ranked a new category , the previous attestation of categories should be changed to revoked? @MoeNick
> > for both of these attestations the "REVOKED" is : No but it seems based on @MoeNick comment, the older attestation should be revoked
> > https://optimism-sepolia.easscan.org/attestation/view/0x7f656d92f15ff1d19fbee8a70bfc4f1279521a1e1f0b3c0403721579ab741eeb
> > https://optimism-sepolia.easscan.org/attestation/view/0x951e2ebcd00e2c4de20eee12db809400ef22e0df7c4369338d58d17b3dad69a5
> > @mmahdigh
> 
> These two attestations have different attesters though?

please check these 2 attestaions @mmahdigh 

https://optimism.easscan.org/attestation/view/0x52ef81171eaf2c46afb25fc8e4331783c8ed37c4410031126c7ada8d917d05f4

https://optimism.easscan.org/attestation/view/0x4914609e02d84e04b1865cfc5ff4d27e1972af475c83aab621794157d8c8bca5

**Comment by maryjaf** [comment]
This attestaion should be revoked 
https://optimism.easscan.org/attestation/view/0x4914609e02d84e04b1865cfc5ff4d27e1972af475c83aab621794157d8c8bca5

when I submit this vote 
https://optimism.easscan.org/attestation/view/0x52ef81171eaf2c46afb25fc8e4331783c8ed37c4410031126c7ada8d917d05f4

@mmahdigh

**Comment by mmahdigh** [comment]
> This attestaion should be revoked https://optimism.easscan.org/attestation/view/0x4914609e02d84e04b1865cfc5ff4d27e1972af475c83aab621794157d8c8bca5
> 
> when I submit this vote https://optimism.easscan.org/attestation/view/0x52ef81171eaf2c46afb25fc8e4331783c8ed37c4410031126c7ada8d917d05f4
> 
> @mmahdigh

This is fixed now. Please do a retest.

**Comment by maryjaf** [comment]
> > This attestaion should be revoked https://optimism.easscan.org/attestation/view/0x4914609e02d84e04b1865cfc5ff4d27e1972af475c83aab621794157d8c8bca5
> > when I submit this vote https://optimism.easscan.org/attestation/view/0x52ef81171eaf2c46afb25fc8e4331783c8ed37c4410031126c7ada8d917d05f4
> > @mmahdigh
> 
> This is fixed now. Please do a retest.

Thanks, it has been fixed
