### ISSUE TITLE
Bug in ranking flow by tapping on "continue ranking"

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-RPGF4#69]
By tapping on "continue ranking" in ranking flow, the page related to "Ranking done" will be shown
I've tested this for different category with 5 or 3 filtered projects and this bug happens to me in these scenarios
but for 4 filtered project it is fine and this bug doesn't happen

My device: iPhone
Browser: Chrome

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/c6d5cdf3-1494-4beb-9041-ccb05c6f9177

@alireza-sharifpour

**Comment by MoeNick** [comment]
I could not reproduce that,

**Comment by MoeNick** [comment]
is it still relevant @maryjaf

**Comment by maryjaf** [comment]
> is it still relevant @maryjaf

continue ranking and finish ranking was removed in this flow.
