### ISSUE TITLE
Set Threshold as 100% and remove the continue ranking modal. 

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#73]
We should remove this and when the threshold is accomplished we move to edit. 

<img width="649" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlpLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3910204154d3c691e6f3d41972f639b7e696257a/image.png" alt="image.png" />

We also should set 100% as the threshold, not the max comparisons.

**Comment by maryjaf** [comment]
This modal has been removed. and user has to compare all his selected projects.
