### ISSUE TITLE
Login/Sign-up with Google

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#8]
As a user, I want to be able to sign up and signing with my Google account to the voting App so I will have another Account Abstracted Address so I can be anonymous and I can play the game simply on my mobile.

**Descriptions:**
1- The user will see a pop-up or customized modal in the voting app open up for Google Login processes, it usually asks for a username, password, and a consent page. If the login is successful user will have to get back to the main page and the new tab (pop-up) will close automatically
2- If user do teh sign-up for first time we create account and assign an AAed Address to the user in the background and we should show the "Pairwise Passport Verified" screen.
3- If the user already has an account and did the sign-up before, we let them sign in we showing a different screen like the above "Account Verified Successfully" 
4- In both above cases after 5 sec user will get redirected to main page automatically 

**Sign-up with Google**
<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fae2e01a4e9aa799dda493d2ac4ebd7fc96fd6be/image.png" alt="image.png" /><img width="367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1842caca3577533a783b86055344e11aab60f273/image.png" alt="image.png" />

**Sign-in with Google:**
<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fae2e01a4e9aa799dda493d2ac4ebd7fc96fd6be/image.png" alt="image.png" /><img width="376" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1qQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9bdaf43b745422558ebd6bf366bc21a6d6dc4fe/image.png" alt="image.png" />

**Design Assets:**
https://www.figma.com/file/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?type=design&node-id=1373-10511&mode=design&t=mkuNIPuKqr8uglIZ-4
https://www.figma.com/file/VeVWDkxYhD8G3AxMFiFYp3/Pairwise-Mobile-Voting-App?type=design&node-id=1373-10712&mode=design&t=mkuNIPuKqr8uglIZ-4

**Comment by MoeNick** [comment]
@mmahdigh @alireza-sharifpour success criteria's updated.

**Comment by maryjaf** [comment]
ُThe test has been passed

**Comment by maryjaf** [comment]
- [ ] This problem also exists in sign with google 

https://github.com/GeneralMagicio/pairwise-RPGF4/issues/10#issuecomment-2112084752

**Comment by mmahdigh** [comment]
> * [ ]  This problem also exists in sign with google
> 
> [#10 (comment)](https://github.com/GeneralMagicio/pairwise-RPGF4/issues/10#issuecomment-2112084752)

[This also has been fixed.](https://github.com/GeneralMagicio/pairwise-RPGF4/issues/10#issuecomment-2120071696)

**Comment by mmahdigh** [comment]
> * [ ]  This problem also exists in sign with google
> 
> [#10 (comment)](https://github.com/GeneralMagicio/pairwise-RPGF4/issues/10#issuecomment-2112084752)

[This also has been fixed.](https://github.com/GeneralMagicio/pairwise-RPGF4/issues/10#issuecomment-2120071696)
