### ISSUE TITLE
handle connect wallet modal when the user isn't connected

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/pairwise-RPGF4#87]
When the user isn't connected,by tapping on "submit vote" button
the wallet connect and switch network to OP should be shown

**Comment by mmahdigh** [comment]
This is ready to test.

**Comment by maryjaf** [comment]
Thanks @mmahdigh this issue has been resolved 

when the user isn't connected, by tapping on a category in main page the wallet connect modal is shown 

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/d8cd68c1-95d2-46d7-97b0-683a0e7b4629
