### ISSUE TITLE
Letting users with no-badge to vote.  

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#90]
User Flow:

- User click on connect or load the connect modal
- when we show the error of no -badge, we can add done button in that screen. 
- User get the proof on connecting in the background.
- connect button in the header will hide but no badges are shown.

**Comment by mmahdigh** [comment]
@maryjaf This is ready for testing.

**Comment by MoeNick** [comment]
Let's change the DONE button to "Connect Anyway"

**Comment by maryjaf** [comment]
should "voting power collected" be shown in this modal when there is no badge? @MoeNick 

![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/3bd77ddc-f5af-4681-a535-c76030c0c265)

**Comment by maryjaf** [comment]
- [ ] I've got an error when I try to submit vote by an user without any badge, please take a look @mmahdigh 

https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/7074ae8b-dc8a-4c2b-b118-291f577367e6

**Comment by MoeNick** [comment]
I was not in the loop for the change of 'Continue as Guest' let's sync and I say it's unnecessary.

**Comment by MoeNick** [comment]
- `Voting Power Connected` should change to '**"You already connected."**

**Comment by MoeNick** [comment]
@mmahdigh Please consider the above changes. Tagging you here again not to miss.

**Comment by mmahdigh** [comment]
> Let's change the DONE button to "Connect Anyway"

This is done. Please retest.

**Comment by maryjaf** [comment]
![image](https://github.com/GeneralMagicio/pairwise-RPGF4/assets/111529185/7ccf5b83-3586-443b-8c48-85aae6298c92)
